### ISSUE TITLE
Blog links

### ISSUE THREAD

**Issue by sagarhani** [fsmk/planet#10]
https://sagarhani.wordpress.com/2014/09/18/facebook-cli/
https://sagarhani.wordpress.com/2014/08/14/linux-is-funnn/
https://sagarhani.wordpress.com/2014/08/26/happy-birthday-linux/
https://sagarhani.wordpress.com/2014/08/29/scrollback-is-awesome/

**Comment by viggyprabhu** [comment]
Fixed after #11 and #12 and b2c10709c6
