### ISSUE TITLE
Feeds from my blog is not appearing on the planet.

### ISSUE THREAD

**Issue by farhaanbukhsh** [fsmk/planet#13]
I checked the feed url it is working pretty fine.

**Comment by viggyprabhu** [comment]
It is fixed now. The issue was that timeoutsocket.py was causing exception for all wordpress related bugs. Fixed it by just deleting the module and running the setup again as suggested in the Fedora Planet bug patch, http://pkgs.fedoraproject.org/cgit/planet.git/commit/?h=epel7
