### ISSUE TITLE
Adding a new Blog

### ISSUE THREAD

**Issue by cyberhck** [fsmk/planet#14]
Me and Harshith written about FSMK Camp on my blog. The list of links to article are given below:
http://nishgtm.com/2015/07/fsmk-summer-camp/
http://nishgtm.com/2015/07/fsmkcamp15/
it has a lot of other technical articles you can go through the blog.

**Comment by viggyprabhu** [comment]
As per [this](https://github.com/fsmk/planet#adding-new-blog), you need to tag all posts that you want to be shown in planet with "FSMK" tag.(I just added that rule in the README.) Also, follow that link on how you can send a PR to add your blog to the planet. It is pretty straight forward. Also dont forget to send a PR for your hackergotchi also.

**Comment by cyberhck** [comment]
What if I don't want to have a hackergotchi now?
